name: kicad-automation

on:
  push:
    paths:
#    - 'hardware/Sparkfun_Trackballer/kicad/*.sch'
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  fabrication:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v1.0
      with:
        cmd: fabrication
        schematic: stm32_dev.sch
        board: stm32_dev.kicad_pcb
        dir: gerbers 
        manufacturer: "jlcpcb"
    - uses: nerdyscout/kicad-exports@v1.0
      with:
        cmd: bom
        schematic: stm32_dev.sch
        board: stm32_dev.kicad_pcb
        dir: bom
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: gerbers
        schematic: stm32_dev.sch
        board: stm32_dev.kicad_pcb
        path: gerbers
