name: kicad-automation

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  fabrication:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#    - uses: nerdyscout/kicad-exports@v2.0
#      with:
#        entryPoint: report
#        schema: hardware/stm32-trackball/stm32_dev.sch
#        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
    - uses: nerdyscout/kicad-exports@v2.0
      with:
        entryPoint: schema
        schema: hardware/stm32-trackball/stm32_dev.sch
        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
        dir: schema
    - uses: nerdyscout/kicad-exports@v2.0
      with:
        entryPoint: kicost
        schema: hardware/stm32-trackball/stm32_dev.sch
        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
        dir: bom
    - uses: nerdyscout/kicad-exports@v2.0
      with:
        entryPoint: pcbdraw-front 
        schema: hardware/stm32-trackball/stm32_dev.sch
        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
        dir: img
    - uses: nerdyscout/kicad-exports@v2.0
      with:
        entryPoint: fabrication
        schema: hardware/stm32-trackball/stm32_dev.sch
        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
        dir: gerbers 
        manufacturer: "jlcpcb"
    - uses: nerdyscout/kicad-exports@v2.0
      with:
        entryPoint: bom
        schema: hardware/stm32-trackball/stm32_dev.sch
        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
        dir: bom
    - name: upload gerbers
      uses: actions/upload-artifact@v2
      with:
        name: gerbers
        schema: hardware/stm32-trackball/stm32_dev.sch
        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
        path: gerbers
