name: kicad-automation

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  fabrication:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - uses: nerdyscout/kicad-exports@v2.0
#      with:
#        cmd: report
#        schematic: hardware/stm32-trackball/stm32_dev.sch
#        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
    - uses: nerdyscout/kicad-exports@v2.0
      with:
        cmd: schematic
        schematic: hardware/stm32-trackball/stm32_dev.sch
        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
        dir: schematic
    - uses: nerdyscout/kicad-exports@v2.0
      with:
        cmd: kicost
        schematic: hardware/stm32-trackball/stm32_dev.sch
        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
        dir: bom
    - uses: nerdyscout/kicad-exports@v2.0
      with:
        cmd: pcbdraw-front 
        schematic: hardware/stm32-trackball/stm32_dev.sch
        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
        dir: img
    - uses: nerdyscout/kicad-exports@v2.0
      with:
        cmd: fabrication
        schematic: hardware/stm32-trackball/stm32_dev.sch
        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
        dir: gerbers 
        manufacturer: "jlcpcb"
    - uses: nerdyscout/kicad-exports@v2.0
      with:
        cmd: bom
        schematic: hardware/stm32-trackball/stm32_dev.sch
        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
        dir: bom
    - name: upload gerbers
      uses: actions/upload-artifact@v2
      with:
        name: gerbers
        schematic: hardware/stm32-trackball/stm32_dev.sch
        board: hardware/stm32-trackball/stm32_dev.kicad_pcb
        path: gerbers
